version: "3.9"

services:
  db:
    image: postgres:15
    container_name: globant_pg
    environment:
      POSTGRES_USER: globant_user
      POSTGRES_PASSWORD: globant_pw
      POSTGRES_DB: globant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
